import{a as y,i as m,S as L}from"./assets/vendor-b42c18af.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function c(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=c(e);fetch(e.href,o)}})();const b="42800800-86f7251243bc7e4391903d90a",w="https://pixabay.com/api/",u=document.querySelector(".loader");let v=15;async function S(t,r){const c=new URLSearchParams({key:b,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:v});u.style.display="block";try{const s=await y.get(`${w}?${c}`);if(!s.status===200)throw new Error("Network response was not OK!");const e=s.data;return u.style.display="none",e.hits.length===0&&m.error({close:!1,messageColor:"#fff",timeout:2e3,backgroundColor:"red",message:"Sorry, there are no images matching your search query. Please try again!"}),e}catch(s){throw console.error("Error fetching data:",s),s}}function f(t){return t.hits.map(r=>`<div class="gallery-item">
      <a class="gallery-link" href="${r.largeImageURL}">
          <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}">
      </a>
      <div class="gallery-image-info">
          <p class="image-info-item"><span class="image-items-text">Likes: </span>${r.likes}</p>
          <p class="image-info-item"><span class="image-items-text">Views: </span>${r.views}</p>
          <p class="image-info-item"><span class="image-items-text">Comments: </span>${r.comments}</p>
          <p class="image-info-item"><span class="image-items-text">Downloads: </span>${r.downloads}</p>
      </div>
  </div>`).join("")}const E=new L(".gallery-link",{captionsData:"alt",captionDelay:250}),g=document.querySelector("#searchForm"),a=document.querySelector(".gallery"),n=document.querySelector(".load-more-btn");let i=1,d=0,p="";n.style.display="none";n.addEventListener("click",x);g.addEventListener("submit",P);a.addEventListener("scroll",$);function P(t){t.preventDefault(),a.innerHTML="",i=1,p=g.elements.searchQuery.value.trim(),h()}function x(){i++,h()}function h(){S(p,i).then(t=>{d=t.totalHits;const r=f(t);a.insertAdjacentHTML("beforeend",r),E.refresh(),H(t)}).catch(t=>console.error("Error fetching data:",t))}function H(t){a.children.length<d?n.style.display="block":i*15>=d?(n.style.display="none",m.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})):f(t)}function $(){const t=a.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:3*t,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
